spring:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true




  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 6636..
            client-secret: GOCS..
            scope:
              - email
              - profile
#          kakao:
#            client-id: 14vdv
#            redirect-uri: 123..
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id

jwt:
  issuer: ajufresh@gmaile.com
  secret_key: study-springboot
  #{OAUTH_CLIENT_ID}{OAUTH_CLIENT_SECRET}{JWT_SECRET_KEY}